package dev.yangsijun.gol.common.common.enums.game

enum class GameModeType(
    val queueId: Int,
    val map: MapType,
    val description: String?
) {
    CUSTOM_GAMES(0, MapType.CUSTOM, null),
    SUMMONERS_RIFT_BLIND_PICK(430, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "5v5 Blind Pick games"),
    SUMMONERS_RIFT_RANKED_SOLO(420, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "5v5 Ranked Solo games"),
    SUMMONERS_RIFT_RANKED_PREMADE(6, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "5v5 Ranked Premade games"),
    SUMMONERS_RIFT_COOP_VS_AI(33, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "Co-op vs AI Intermediate Bot games"),
    TWISTED_TREELINE_NORMAL(460, MapType.TWISTED_TREELINE_ORIGINAL, "3v3 Normal games"),
    TWISTED_TREELINE_RANKED_FLEX(470, MapType.TWISTED_TREELINE_ORIGINAL, "3v3 Ranked Flex games"),
    SUMMONERS_RIFT_DRAFT_PICK(400, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "5v5 Draft Pick games"),
    HOWLING_ABYSS_ARAM(450, MapType.HOWLING_ABYSS, "5v5 ARAM games"),
    HOWLING_ABYSS_1V1_SHOWDOWN(72, MapType.HOWLING_ABYSS, "1v1 Snowdown Showdown games"),
    HOWLING_ABYSS_2V2_SHOWDOWN(73, MapType.HOWLING_ABYSS, "2v2 Snowdown Showdown games"),
    SUMMONERS_RIFT_6V6(75, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "6v6 Hexakill games"),
    SUMMONERS_RIFT_ULTRA_RAPID_FIRE(76, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "Ultra Rapid Fire games"),
    HOWLING_ABYSS_ONE_FOR_ALL(78, MapType.HOWLING_ABYSS, "One For All: Mirror Mode games"),
    SUMMONERS_RIFT_ARURF(900, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "ARURF games"),
    CRYSTAL_SCAR_ASCENSION(910, MapType.THE_CRYSTAL_SCAR, "Ascension games"),
    HOWLING_ABYSS_LEGEND_OF_THE_PORO_KING(920, MapType.HOWLING_ABYSS, "Legend of the Poro King games"),
    SUMMONERS_RIFT_NEXUS_SIEGE(940, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "Nexus Siege games"),
    SUMMONERS_RIFT_ALL_RANDOM(325, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "All Random games"),
    SUMMONERS_RIFT_RANKED_DYNAMIC(410, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "5v5 Ranked Dynamic games"),
    TWISTED_TREELINE_COOP_VS_AI_BEGINNER(820, MapType.TWISTED_TREELINE_ORIGINAL, "Co-op vs. AI Beginner Bot games"),
    SUMMONERS_RIFT_COOP_VS_AI_INTRO(830, MapType.SUMMONERS_RIFT_SUMMER_VARIANT, "Co-op vs. AI Intro Bot games")
}
