server:
  port: 8080
spring:
  data:
    mongodb:
      auto-index-creation: true

gauth:
  client-id:
  client-secret:
  redirect-uri:

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
