server:
  port: 8080
spring:
  data:
    mongodb:
      auto-index-creation: true

riot:
  api-key: ${API_KEY}

gauth:
  client-id: "9e3c6c50d13c408396a64768505f58e88791cab81502424bb49c60577d7608d7"
  client-secret: ${GAUTH_CLIENT_SECRET}
  redirect-uri: http://localhost:8080/login/code/gauth


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    dev:
      yangsijun:
        gol: DEBUG
